import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { granolaFont } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${granolaFont.variable} font-sans antialiased  text-black`}>
        <Navbar />
        <main className="min-h-screen grid">
          {/* <div className="overflow-visible absolute inset-0 select-none z-[-1] opacity-60 rotate-180 bg-[radial-gradient(at_53%_78%,rgba(255,255,0,0.3)_0px,transparent_50%),radial-gradient(at_71%_91%,rgba(51,255,0,0.3)_0px,transparent_50%),radial-gradient(at_31%_91%,rgba(255,128,0,0.17)_0px,transparent_50%)]"></div> */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
